# fly.toml app configuration file generated for aiesec-scraper-v1 on 2024-02-06T02:34:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aiesec-scraper-v1"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 1024
